import "dotenv/config";
import fs from "node:fs/promises";
import path from "node:path";

type ScrapedPost = {
  body: string;
  platform: "linkedin" | "x";
};

async function main() {
  const linkedinHandle = process.env.OWN_LINKEDIN_HANDLE;
  const xHandle = process.env.OWN_X_HANDLE;
  const posts = await scrapeOwnedPosts(linkedinHandle, xHandle);
  const summary = distillVoiceSamples(posts);
  const target = path.resolve(process.cwd(), "src/content/brand/voice-samples.md");

  await fs.writeFile(target, summary, "utf8");
  console.log(`[ingest:handles] wrote ${target}`);
}

async function scrapeOwnedPosts(linkedinHandle?: string, xHandle?: string): Promise<ScrapedPost[]> {
  void linkedinHandle;
  void xHandle;
  // TODO: import from slice A — using stub until src/lib/content/scraper.ts lands.
  return [];
}

function distillVoiceSamples(posts: ScrapedPost[]): string {
  const recent = posts.slice(-50);
  const linkedin = recent.filter((post) => post.platform === "linkedin");
  const x = recent.filter((post) => post.platform === "x");

  return [
    "# Voice Samples",
    "",
    "> Generated by `pnpm ingest:handles` from the last 50 owned posts. Hand-written seed samples remain below until Slice A scraping is available.",
    "",
    "## Mined Summary",
    "",
    `Posts analyzed: ${recent.length}`,
    "",
    "### Themes",
    summarizeThemes(recent),
    "",
    "### Opener Patterns",
    summarizeOpeners(recent),
    "",
    "### CTA Patterns",
    summarizeCtas(recent),
    "",
    "## Source Counts",
    "",
    `- LinkedIn: ${linkedin.length}`,
    `- X: ${x.length}`,
    "",
    "## Hand-Written LinkedIn Samples",
    "",
    fallbackLinkedInSamples(),
    "",
    "## Hand-Written X Samples",
    "",
    fallbackXSamples(),
  ].join("\n");
}

function summarizeThemes(posts: ScrapedPost[]): string {
  if (posts.length === 0) return "- No owned posts available yet.";
  const keywords = ["AI", "workflow", "prototype", "rebuild", "handoff", "audit", "MVP", "integration"];
  return keywords
    .map((keyword) => ({
      keyword,
      count: posts.filter((post) => post.body.toLowerCase().includes(keyword.toLowerCase())).length,
    }))
    .filter((item) => item.count > 0)
    .sort((a, b) => b.count - a.count)
    .map((item) => `- ${item.keyword}: ${item.count} mentions`)
    .join("\n") || "- No repeated themes detected.";
}

function summarizeOpeners(posts: ScrapedPost[]): string {
  const openers = posts
    .map((post) => post.body.split(/\r?\n/).find((line) => line.trim().length > 0)?.trim())
    .filter((line): line is string => Boolean(line))
    .slice(0, 10);
  return openers.length ? openers.map((line) => `- ${line}`).join("\n") : "- No opener patterns available yet.";
}

function summarizeCtas(posts: ScrapedPost[]): string {
  const ctas = posts
    .map((post) => post.body.split(/\r?\n/).reverse().find((line) => line.trim().length > 0)?.trim())
    .filter((line): line is string => Boolean(line))
    .filter((line) => /dm|send|reply|call|audit|link|tell me/i.test(line))
    .slice(0, 10);
  return ctas.length ? ctas.map((line) => `- ${line}`).join("\n") : "- No CTA patterns available yet.";
}

function fallbackLinkedInSamples(): string {
  return [
    "### LinkedIn 1",
    "The demo is not the product. The product is what happens after the third weird customer input.",
    "",
    "Most AI workflow builds look solid in the happy path. Production starts when validation, review queues, permissions, and rollback paths exist around the model call.",
    "",
    "Working on this now? Send the workflow. I will point out the riskiest part.",
    "",
    "### LinkedIn 2",
    "Most rebuilds do not fail because the old app was messy. They fail because the team never names what has to stay boring.",
    "",
    "Keep the proven workflow intact. Replace the weak boundaries first: brittle integrations, manual admin steps, unclear ownership, and missing tests around revenue paths.",
    "",
    "A rebuild should buy speed after launch, not a prettier way to stall before it.",
    "",
    "### LinkedIn 3",
    "The fastest SaaS teams are not the teams with the most code. They are the teams with the fewest unclear handoffs.",
    "",
    "When we audit a product, we look less at the feature list and more at who waits, who copies data, who approves, who fixes the weird case, and who knows something broke.",
    "",
    "That is usually where the roadmap is hiding.",
  ].join("\n");
}

function fallbackXSamples(): string {
  return [
    "1. The demo is not the product. The product is the retry path, the audit trail, the weird input, and the support log when the model gets it wrong.",
    "",
    "2. Most AI features should start as a workflow audit. If the human process is unclear, the model will only make the confusion faster.",
    "",
    "3. A rebuild is a bet that tighter boundaries will make every future feature cheaper.",
    "",
    "4. Good founder software removes decisions. Bad founder software adds dashboards for decisions nobody owns.",
    "",
    "5. The best MVP scope is not the smallest thing you can demo. It is the smallest thing a real customer can use twice without your team standing next to it.",
  ].join("\n");
}

main().catch((err) => {
  console.error("[ingest:handles]", err instanceof Error ? err.message : err);
  process.exitCode = 1;
});
